Enable ffmpeg support
flathub/net.sf.VICE pull request #28
Opened 2022-06-22 14:15 UTC by binaryfields

2022-06-25 17:41 UTC, binaryfields commented
Fixes #27

2022-10-14 10:11 UTC, Brog33 commented
could you make a new build so i can test it?

2022-10-14 15:51 UTC, hfiguiere commented
bot, build

2022-12-19 02:44 UTC, hfiguiere commented
bot, build

2022-12-19 02:44 UTC, hfiguiere commented
I'll test and merge

2022-12-19 02:45 UTC, hfiguiere commented
Close #27

2022-12-19 03:51 UTC, hfiguiere commented
Actually this doesn't work and nobody reported it.

Start VICE and it terminates early.

If you start wth `--verbose` you get:

```
Cannot set string resource 'FFMPEGFormat' to default 'mp4'
Cannot set defaults.
```

ffmpeg needs to be built with mp4 support.

2022-12-19 04:05 UTC, hfiguiere commented on net.sf.VICE.yml
> +    add-ld-path: .
```suggestion
    org.freedesktop.Platform.ffmpeg-full: 
        directory: lib/ffmpeg
        version: '21.08'
        add-ld-path: .
```

This is the proper syntax.

It even complain with `(flatpak-builder:2): Json-WARNING **: 02:44:55.926: Failed to deserialize "add-extensions" property of type "gpointer" for an object of type "BuilderManifest"`

Also `(flatpak-builder:2): flatpak-builder-WARNING **: 02:44:55.925: 16:14: '21.08' will be parsed as a number by many YAML parsers`

(YAML is amazing)

2022-12-19 19:40 UTC, hfiguiere requested changes
With the suggested fix it should work.

2022-12-19 19:40 UTC, hfiguiere commented on net.sf.VICE.yml
> +  - mkdir -p /app/lib/ffmpeg
```suggestion
  - --env=LD_LIBRARY_PATH=/app/lib/codecs/lib
```

Actually all you need is this.

2022-12-19 19:41 UTC, hfiguiere commented on net.sf.VICE.yml
> +    add-ld-path: .
Just ignore this, see suggestio below.

2022-12-20 01:58 UTC, closed without merging